site_name: Introducción a Linux

theme:
  name: material

nav:
  - Inicio: index.md
  - Sección 1 - Introducción:
    - Introducción: seccion1/introduccion.md
    - Planeación: seccion1/archivos/Planeación.pdf
    - Prueba de desempeño: seccion1/archivos/Prueba_de_desempeño_inicial.pdf
    - ¿Qué distribución puedo usar?: seccion1/distribución.md
    - Instalar Linux en mi PC: seccion1/installar-linux.md
    - Introducción a Linux. ¿Qué es un shell?: seccion1/
  - Sección 2 - Primeros pasos en el intérprete de comandos BASH:
    - Acceso al emulador de terminal en el enterno de ventanas: seccion2/
    - Descripción del entorno Bash: seccion2/
    - Construcción de una orden Comando, Opciones y Argumento: seccion2/construccion-de-una-orden.md
    - La importancia de los espacios y las mayúsculas: seccion2/
    - Conseguir ayuda en linux: seccion2/comandos-ayuda.png
    - Resumen de la sección: seccion2/resumen.png
  - Sección 3 - Comados del sistema de ficheros:
    - Actividad de retroalimentación grupal: seccion3/actividad.md
  #- Sección 4 - Usuarios y permisos:
  #- Sección 5 - Administración de software:
  #- Sección 6 - Mostrar y filtrar texto:
  #- Sección 7 - Tuberias y redirecciones:
  #- Sección 8 - Acciones sobre texto:
  #- Sección 9 - Otros comandos del sistema de ficheros:
  #- Sección 10 - Búsquedas en el sistema de ficheros:
  #- Sección 11 - Ampliando conocimientos del Shell Bash de Linux:
  #- Sección 12 - Comprime y crea copias de seguridad (Backups):
  #- Sección 13 - Gestión de paquetes con dpkg:
  #- Sección 14 - Administración de usuarios, grupos y contraseñas:
