site_name: Introducción a Linux

theme:
  name: material

nav:
  - Inicio: index.md
  - Sección 1 - Introducción:
    - Introducción: seccion1/introduccion.md
    - Planeación: seccion1/archivos/Planeación.pdf
    - Prueba de desempeño: seccion1/archivos/Prueba_de_desempeño_inicial.pdf
    - ¿Qué distribución puedo usar?: seccion1/distribución.md
    - Instalar Linux en mi PC: seccion1/instalar-linux.md
    - Introducción a Linux. ¿Qué es un shell?: seccion1/shell.md
  - Sección 2 - Primeros pasos en el intérprete de comandos BASH:
    - Construcción de una orden Comando, Opciones y Argumento: seccion2/construccion-de-una-orden.md
    - La importancia de los espacios y las mayúsculas: seccion2/mayusculas.md
    - Conseguir ayuda en linux: seccion2/comandos-ayuda.png
    - Resumen de la sección: seccion2/resumen.png
  - Sección 3 - Comados del sistema de ficheros:
    - Navegar por los directorios comando cd y ls: seccion3/navegarDir.jpg
    - Comando TYPE: seccion3/type.jpg
    - Comando SUDO: seccion3/sudo.jpg
    - Rutas absolutas-relativas: seccion3/rutas.md
    - Uso de comodines: seccion3/comodines.md
    - Evidencias: seccion3/evidencias.md
  - Sección 4 - Usuarios y permisos:
    - Información sobre usuarios y grupos: seccion4/usuario1.jpg
    - Información sobre usuarios y grupos: seccion4/usuario2.jpg
    - Crear usuarios y grupos: seccion4/usuario3.jpg
    - Crear usuarios y grupos: seccion4/usuario4.jpg
    - Los permisos en los ficheros y cambiar de permisos: seccion4/permisos.pdf
  - Sección 5 - Administración de software:
    - Configuración de repositorios_Gestión de software en Linux (apt): seccion5/software.md
  - Sección 6 - Mostrar y filtrar texto:
    - Mostrar texto comando ECHO: seccion6/ECHO.md
    - Mostrando texto comando CAT: seccion6/CAT.md
    - Seleccionar partes de una línea comando CUT: seccion6/CUT.md
  - Sección 7 - Tuberias y redirecciones:
    - Ver sección 7: seccion7/
  - Sección 8 - Acciones sobre texto:
    - Manos a la obra: seccion8/texto.md
  - Sección 9 - Otros comandos del sistema de ficheros:
    - Sistema de ficheros(archivo 1): seccion9/H6N1-Taiwan.fa
    - Comando FILE: seccion9/FILE.md
    - Comando ln: seccion9/LN.md
  - Sección 10 - Búsquedas en el sistema de ficheros:
    - Comando LOCATE: seccion10/locate.md
    - Comando FIND: seccion10/find.md
  - Sección 11 - Ampliando conocimientos del Shell Bash de Linux:
    - Acortar líneas de ordenes: seccion11/alias.md
    - Variables de entorno y sustitución de comandos: seccion11/var-ent.md
  - Sección 12 - Comprime y crea copias de seguridad Backups:
    - Compresión de archivos con TAR: seccion12/tar.md
    - Resumen: seccion12/resumen.pdf
  - Sección 13 - Gestión de paquetes con dpkg:
    - Comando para administrar paquetes sin repositorios dpkg: seccion13/dpkg.md
  - Sección 14 - Administración de usuarios, grupos y contraseñas:
    - Adminstración de usuariós grupos y contraseñas: seccion14/contrasienas.md
    - Comodin1 barra bin barra bash: seccion14/barrabin.md
    - Comodin2 rsync: seccion14/rsync.md
